server:
  port: 60922
  address: 127.0.0.1

spring:
  application:
    name: "webProgramming"
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/webprogramming?serverTimezone=Asia/Taipei&characterEncoding=utf-8"
    username: "root"
    password: "Margaret20070922"