server:
  port: 60922
  address: 127.0.0.1
  shutdown: "graceful"

# 暴露 shutdown 接口
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: shutdown

spring:
  application:
    name: "webProgramming"
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/webprogramming?serverTimezone=Asia/Taipei&characterEncoding=utf-8"
    username: "root"
    password: "Margaret20070922"